In [137]:
import numpy as np 
import pandas as pd 
import os

In [138]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

train.head()
train.info()
train.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [139]:
train.isnull().sum().sort_values(ascending=False).head(20)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
LotFrontage      259
GarageQual        81
GarageFinish      81
GarageType        81
GarageYrBlt       81
GarageCond        81
BsmtFinType2      38
BsmtExposure      38
BsmtCond          37
BsmtQual          37
BsmtFinType1      37
MasVnrArea         8
Electrical         1
Condition2         0
dtype: int64

# cleaning

## cleaning_v1_semantic_imputation

In [140]:
df = train.copy()

In [141]:
none_cols = [
    "PoolQC", "MiscFeature", "Alley", "Fence", "FireplaceQu",
    "GarageType", "GarageFinish", "GarageQual", "GarageCond",
    "BsmtQual", "BsmtCond", "BsmtExposure", "BsmtFinType1", "BsmtFinType2"
]

for col in none_cols:
    df[col] = df[col].fillna("None")

In [142]:
df["LotFrontage"] = df.groupby("Neighborhood")["LotFrontage"].transform(
    lambda x: x.fillna(x.median())
) 
df["MasVnrType"] = df["MasVnrType"].fillna("None")
df["MasVnrArea"] = df["MasVnrArea"].fillna(0)
df["GarageYrBlt"] = df["GarageYrBlt"].fillna(0)
df["Electrical"] = df["Electrical"].fillna(df["Electrical"].mode()[0])

In [143]:
print("Remaining missing values:", df.isnull().sum().sum())

Remaining missing values: 0

In [144]:
!pip install dagshub mlflow
import dagshub
dagshub.init(repo_owner='smama23', repo_name='MLassignment1', mlflow=True)

import mlflow

with mlflow.start_run(run_name="cleaning_v1"):
    mlflow.log_param("missing_strategy", "semantic + group_median")
    mlflow.log_param("LotFrontage", "median_by_neighborhood")
    mlflow.log_param("MasVnrArea", "fill_0")
    mlflow.log_param("GarageYrBlt", "fill_0")
    mlflow.log_param("Electrical", "mode")

    mlflow.log_metric("remaining_missing", df.isnull().sum().sum())

Requirement already satisfied: dagshub in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (0.6.9)
Requirement already satisfied: mlflow in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (3.11.1)
Requirement already satisfied: PyYAML>=5 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (6.0.3)
Requirement already satisfied: appdirs>=1.4.4 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (1.4.4)
Requirement already satisfied: click>=8.0.4 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (8.2.1)
Requirement already satisfied: httpx>=0.23.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (0.28.1)
Requirement already satisfied: GitPython>=3.1.29 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (3.1.46)
Requirement already satisfied: rich>=13.1.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (14.3.3)
Requirement already satisfied: dacite~=1.6.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (1.6.0)
Requirement already satisfied: tenacity>=8.2.2 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (9.1.4)
Requirement already satisfied: gql[requests] in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (4.0.0)
Requirement already satisfied: dataclasses-json in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (0.6.7)
Requirement already satisfied: pandas in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (2.3.3)
Requirement already satisfied: treelib>=1.6.4 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (1.8.0)
Requirement already satisfied: pathvalidate>=3.0.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (3.3.1)
Requirement already satisfied: python-dateutil in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (2.9.0.post0)
Requirement already satisfied: boto3 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (1.42.87)
Requirement already satisfied: semver in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (3.0.4)
Requirement already satisfied: dagshub-annotation-converter>=0.1.12 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub) (0.1.16)
Requirement already satisfied: mlflow-skinny==3.11.1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (3.11.1)
Requirement already satisfied: mlflow-tracing==3.11.1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (3.11.1)
Requirement already satisfied: Flask-CORS<7 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (6.0.2)
Requirement already satisfied: Flask<4 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (3.13.3)
Requirement already satisfied: alembic!=1.10.0,<2 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<47,>=43.0.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (46.0.7)
Requirement already satisfied: docker<8,>=4.0.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (7.1.0)
Requirement already satisfied: graphene<4 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (3.4.3)
Requirement already satisfied: huey<3,>=2.5.4 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (2.6.0)
Requirement already satisfied: matplotlib<4 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (3.10.8)
Requirement already satisfied: numpy<3 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (2.4.3)
Requirement already satisfied: pyarrow<24,>=4.0.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (23.0.1)
Requirement already satisfied: scikit-learn<2 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (1.8.0)
Requirement already satisfied: scipy<2 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (1.17.1)
Requirement already satisfied: skops<1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (0.13.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (2.0.49)
Requirement already satisfied: waitress<4 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow) (3.0.2)
Requirement already satisfied: cachetools<8,>=5.0.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (7.0.5)
Requirement already satisfied: cloudpickle<4 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (0.102.0)
Requirement already satisfied: fastapi<1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (0.135.3)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (1.41.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (1.41.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (1.41.0)
Requirement already satisfied: packaging<27 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (25.0)
Requirement already satisfied: protobuf<8,>=3.12.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (6.33.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (2.12.5)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (1.2.2)
Requirement already satisfied: requests<3,>=2.17.3 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (2.32.5)
Requirement already satisfied: sqlparse<1,>=0.4.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (0.5.5)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (0.44.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from aiohttp<4->mlflow) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from aiohttp<4->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from aiohttp<4->mlflow) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from aiohttp<4->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from aiohttp<4->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from aiohttp<4->mlflow) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from aiohttp<4->mlflow) (1.23.0)
Requirement already satisfied: Mako in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from alembic!=1.10.0,<2->mlflow) (1.3.10)
Requirement already satisfied: colorama in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from click>=8.0.4->dagshub) (0.4.6)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from cryptography<47,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: google-auth~=2.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (2.49.2)
Requirement already satisfied: pywin32>=304 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from docker<8,>=4.0.0->mlflow) (311)
Requirement already satisfied: urllib3>=1.26.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from docker<8,>=4.0.0->mlflow) (2.6.3)
Requirement already satisfied: starlette>=0.46.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (1.0.0)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.0.4)
Requirement already satisfied: blinker>=1.9.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from Flask<4->mlflow) (3.0.2)
Requirement already satisfied: werkzeug>=3.1.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from Flask<4->mlflow) (3.1.8)
Requirement already satisfied: gitdb<5,>=4.0.1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from GitPython>=3.1.29->dagshub) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from gitdb<5,>=4.0.1->GitPython>=3.1.29->dagshub) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (0.4.2)
Requirement already satisfied: graphql-core<3.3,>=3.1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from graphene<4->mlflow) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: zipp>=3.20 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.11.1->mlflow) (3.23.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from matplotlib<4->mlflow) (4.61.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from matplotlib<4->mlflow) (1.4.9)
Requirement already satisfied: pillow>=8 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from matplotlib<4->mlflow) (12.1.1)
Requirement already satisfied: pyparsing>=3 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from matplotlib<4->mlflow) (3.2.5)
Requirement already satisfied: opentelemetry-semantic-conventions==0.62b0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.11.1->mlflow) (0.62b0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from pandas->dagshub) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from pandas->dagshub) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.11.1->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.11.1->mlflow) (2.41.5)
Requirement already satisfied: six>=1.5 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from python-dateutil->dagshub) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (2026.1.4)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from scikit-learn<2->mlflow) (3.5.0)
Requirement already satisfied: prettytable>=3.9 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet>=1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.4.0)
Requirement already satisfied: h11>=0.8 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from uvicorn<1->mlflow-skinny==3.11.1->mlflow) (0.16.0)
Requirement already satisfied: pycparser in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from cffi>=2.0.0->cryptography<47,>=43.0.0->mlflow) (2.23)
Requirement already satisfied: lxml in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dagshub-annotation-converter>=0.1.12->dagshub) (6.0.3)
Requirement already satisfied: anyio in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from httpx>=0.23.0->dagshub) (4.12.1)
Requirement already satisfied: httpcore==1.* in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: wcwidth in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.2.14)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (0.6.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from rich>=13.1.0->dagshub) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from rich>=13.1.0->dagshub) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub) (0.1.2)
Requirement already satisfied: botocore<1.43.0,>=1.42.87 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from boto3->dagshub) (1.42.87)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from boto3->dagshub) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from boto3->dagshub) (0.16.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dataclasses-json->dagshub) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from dataclasses-json->dagshub) (0.9.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub) (1.1.0)
Requirement already satisfied: backoff<3.0,>=1.11.1 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from gql[requests]->dagshub) (2.2.1)
Requirement already satisfied: requests_toolbelt<2,>=1.0.0 in C:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from gql[requests]->dagshub) (1.0.0)

Initialized MLflow to track repo "smama23/MLassignment1"

Repository smama23/MLassignment1 initialized!

🏃 View run cleaning_v1 at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0/runs/8b17adb9b1cd4ce099ee529234a4ff38
🧪 View experiment at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0

In [145]:
df.isnull().sum().sort_values(ascending=False).head(10)

Id             0
MSSubClass     0
MSZoning       0
LotFrontage    0
LotArea        0
Street         0
Alley          0
LotShape       0
LandContour    0
Utilities      0
dtype: int64

# Feature Engineering

In [146]:
df_encoded = df.copy()

In [147]:
qual_map = {
    "None": 0,
    "Po": 1,
    "Fa": 2,
    "TA": 3,
    "Gd": 4,
    "Ex": 5
}

In [148]:
qual_cols = [
    "ExterQual", "ExterCond",
    "BsmtQual", "BsmtCond",
    "HeatingQC",
    "KitchenQual",
    "FireplaceQu",
    "GarageQual", "GarageCond",
    "PoolQC"
]

for col in qual_cols:
    df_encoded[col] = df_encoded[col].map(qual_map)

In [149]:
df_encoded[qual_cols].head()

,ExterQual,ExterCond,BsmtQual,BsmtCond,HeatingQC,KitchenQual,FireplaceQu,GarageQual,GarageCond,PoolQC
0,4,3,4,3,5,4,0,3,3,0
1,3,3,4,3,5,3,3,3,3,0
2,4,3,4,3,5,4,3,3,3,0
3,3,3,3,4,4,4,4,3,3,0
4,4,3,4,3,5,4,3,3,3,0

In [150]:
with mlflow.start_run(run_name="encoding_v1"):
    mlflow.log_param("encoding", "ordinal_quality_mapping_0_to_5")

🏃 View run encoding_v1 at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0/runs/9b308e90be874534a33bbe50bc234554
🧪 View experiment at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0

In [151]:
df_encoded.select_dtypes(include="object").columns

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'Foundation', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinType2', 'Heating', 'CentralAir', 'Electrical',
       'Functional', 'GarageType', 'GarageFinish', 'PavedDrive', 'Fence',
       'MiscFeature', 'SaleType', 'SaleCondition'],
      dtype='object')

In [152]:
df_final = df_encoded.copy()

In [153]:
df_final = pd.get_dummies(df_final)

In [154]:
df_final = df_final[
    ~((df_final["GrLivArea"] > 4000) & (df_final["SalePrice"] < 200000))
].copy()

print("Removed outliers. New shape:", df_final.shape)

Removed outliers. New shape: (1458, 264)

In [155]:
print(df_final.shape)

(1458, 264)

In [156]:
df_final.select_dtypes(include="object").columns

Index([], dtype='object')

In [157]:
with mlflow.start_run(run_name="encoding_v2_onehot"):
    mlflow.log_param("encoding", "one_hot_all_nominal")
    mlflow.log_metric("num_features", df_final.shape[1])

🏃 View run encoding_v2_onehot at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0/runs/900e2d2aa80945d3ac4beb8bf8207b8c
🧪 View experiment at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0

In [158]:
X = df_final.drop("SalePrice", axis=1)
y = df_final["SalePrice"]

In [159]:
import numpy as np

y = np.log1p(y)

In [160]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [161]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [162]:
y_pred = model.predict(X_val)

In [163]:
from sklearn.metrics import mean_squared_error

rmse = np.sqrt(mean_squared_error(y_val, y_pred))
print("RMSE:", rmse)

RMSE: 0.1301446343267266

In [164]:
import mlflow

with mlflow.start_run(run_name="baseline_linear_regression"):
    mlflow.log_param("model", "LinearRegression")
    mlflow.log_param("features", df_final.shape[1])
    mlflow.log_metric("rmse", rmse)

🏃 View run baseline_linear_regression at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0/runs/82ba30321bd645a28159444ddd2b8331
🧪 View experiment at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0

In [165]:
rmse

np.float64(0.1301446343267266)

In [166]:
from sklearn.linear_model import Ridge

ridge = Ridge(alpha=10)
ridge.fit(X_train, y_train)

Ridge(alpha=10)

In [167]:
y_pred_ridge = ridge.predict(X_val)

In [168]:
rmse_ridge = np.sqrt(mean_squared_error(y_val, y_pred_ridge))
print("Ridge RMSE:", rmse_ridge)

Ridge RMSE: 0.12194757957385126

In [169]:
with mlflow.start_run(run_name="ridge_alpha_10"):
    mlflow.log_param("model", "Ridge")
    mlflow.log_param("alpha", 10)
    mlflow.log_metric("rmse", rmse_ridge)

🏃 View run ridge_alpha_10 at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0/runs/e56ebea6e02c44ed8306a5f8ae97e5d8
🧪 View experiment at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0

# Feature Selection

In [170]:
import pandas as pd
import numpy as np

corr = pd.concat([X_train, y_train], axis=1).corr()["SalePrice"].abs()

selected_features = corr[corr > 0.05].index.drop("SalePrice")

X_train_sel = X_train[selected_features]
X_val_sel = X_val[selected_features]

In [171]:
ridge_sel = Ridge(alpha=10)
ridge_sel.fit(X_train_sel, y_train)

y_pred_sel = ridge_sel.predict(X_val_sel)

rmse_sel = np.sqrt(mean_squared_error(y_val, y_pred_sel))
print("Selected Features RMSE:", rmse_sel)

Selected Features RMSE: 0.12599562603692

In [172]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
import numpy as np

alphas = [0.1, 1, 5, 10, 50, 100]

results = []

for a in alphas:
    model = Ridge(alpha=a)
    model.fit(X_train, y_train)
    preds = model.predict(X_val)
    rmse = np.sqrt(mean_squared_error(y_val, preds))
    results.append((a, rmse))

results

[(0.1, np.float64(0.12781351624093948)),
 (1, np.float64(0.12255920837103478)),
 (5, np.float64(0.12161710552233268)),
 (10, np.float64(0.12194757957385126)),
 (50, np.float64(0.12347096092482458)),
 (100, np.float64(0.12515123378106996))]

In [173]:
with mlflow.start_run(run_name="ridge_best_alpha_0_1"):
    mlflow.log_param("model", "Ridge")
    mlflow.log_param("alpha", 0.1)
    mlflow.log_metric("rmse", 0.12409264369272437)

🏃 View run ridge_best_alpha_0_1 at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0/runs/a01781bde37c465796a60b088c25afae
🧪 View experiment at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0

In [174]:
X_manual = X_train.copy()
X_val_manual = X_val.copy()

In [175]:
drop_cols = [
    "Alley",
    "PoolQC",
    "Fence",
    "MiscFeature",
    "Id"
]

X_manual = X_manual.drop(columns=drop_cols, errors="ignore")
X_val_manual = X_val_manual.drop(columns=drop_cols, errors="ignore")

In [176]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
import numpy as np

model_manual = Ridge(alpha=0.1)
model_manual.fit(X_manual, y_train)

preds_manual = model_manual.predict(X_val_manual)

rmse_manual = np.sqrt(mean_squared_error(y_val, preds_manual))

print("Manual Drop RMSE:", rmse_manual)

Manual Drop RMSE: 0.12788150180168742

In [177]:
with mlflow.start_run(run_name="manual_feature_drop_ridge"):
    mlflow.log_param("features_removed", drop_cols)
    mlflow.log_param("model", "Ridge")
    mlflow.log_param("alpha", 0.1)
    mlflow.log_metric("rmse", rmse_manual)

🏃 View run manual_feature_drop_ridge at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0/runs/2b0cdc0f970f48b996046225ba165fdd
🧪 View experiment at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0

## Feature Engineering v3 - Interaction Features

In [178]:
df_inter = df.copy()

In [179]:
df_inter = df.copy()

df_inter["HouseAge"] = df_inter["YrSold"] - df_inter["YearBuilt"]
df_inter["RemodAge"] = df_inter["YrSold"] - df_inter["YearRemodAdd"]

df_inter["OverallQual_GrLivArea"] = df_inter["OverallQual"] * df_inter["GrLivArea"]
df_inter["BsmtQual_TotalBsmtSF"] = df_inter["BsmtQual"] * df_inter["TotalBsmtSF"]
df_inter["GarageStrength"] = df_inter["GarageCars"] * df_inter["GarageArea"]
df_inter["HouseAge_Quality"] = df_inter["HouseAge"] * df_inter["OverallQual"]
df_inter["Remod_Quality"] = df_inter["RemodAge"] * df_inter["OverallQual"]

In [180]:
df_inter["TotalSF"] = (
    df_inter["TotalBsmtSF"] +
    df_inter["1stFlrSF"] +
    df_inter["2ndFlrSF"]
)

In [181]:
df_inter = pd.get_dummies(df_inter)

In [182]:
import numpy as np

X = df_inter.drop("SalePrice", axis=1)
y = np.log1p(df_inter["SalePrice"])

In [183]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [184]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
import numpy as np

model = Ridge(alpha=0.1)
model.fit(X_train, y_train)

preds = model.predict(X_val)

rmse_inter = np.sqrt(mean_squared_error(y_val, preds))

print("Interaction Features RMSE:", rmse_inter)

Interaction Features RMSE: 0.14177473668913407

In [185]:
import mlflow

with mlflow.start_run(run_name="ridge_interaction_features_v3"):
    mlflow.log_param("feature_engineering", "interaction_features_v3")
    mlflow.log_param("features_added", [
        "OverallQual_GrLivArea",
        "BsmtQual_TotalBsmtSF",
        "GarageStrength",
        "HouseAge_Quality",
        "Remod_Quality"
    ])
    mlflow.log_param("model", "Ridge")
    mlflow.log_param("alpha", 0.1)
    mlflow.log_metric("rmse", rmse_inter)

🏃 View run ridge_interaction_features_v3 at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0/runs/e9b515776da34ade9a5dbc1fda55ef4c
🧪 View experiment at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0

In [186]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

In [187]:
gbr = GradientBoostingRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gbr.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=0.05, n_estimators=300, random_state=42)

In [188]:
preds = gbr.predict(X_val)

rmse_gbr = np.sqrt(mean_squared_error(y_val, preds))

print("Gradient Boosting RMSE:", rmse_gbr)

Gradient Boosting RMSE: 0.13624247356628635

In [189]:
import mlflow

with mlflow.start_run(run_name="gradient_boosting_v1"):
    mlflow.log_param("model", "GradientBoostingRegressor")
    mlflow.log_param("n_estimators", 300)
    mlflow.log_param("learning_rate", 0.05)
    mlflow.log_param("max_depth", 3)

    mlflow.log_metric("rmse", rmse_gbr)

🏃 View run gradient_boosting_v1 at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0/runs/3498b2c826654f968e661c0423e522a0
🧪 View experiment at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0

In [190]:
%pip install xgboost
from xgboost import XGBRegressor 

xgb = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb.fit(X_train, y_train)

Requirement already satisfied: xgboost in c:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from xgboost) (2.4.3)
Requirement already satisfied: scipy in c:\Users\User\anaconda3\envs\cs224n\Lib\site-packages (from xgboost) (1.17.1)
Note: you may need to restart the kernel to use updated packages.

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [191]:
preds_xgb = xgb.predict(X_val)

rmse_xgb = np.sqrt(mean_squared_error(y_val, preds_xgb))

print("XGBoost RMSE:", rmse_xgb)

XGBoost RMSE: 0.13490211466466867

In [192]:
with mlflow.start_run(run_name="xgboost_v1"):
    mlflow.log_param("model", "XGBRegressor")
    mlflow.log_param("n_estimators", 500)
    mlflow.log_param("learning_rate", 0.05)
    mlflow.log_param("max_depth", 4)
    mlflow.log_param("subsample", 0.8)
    mlflow.log_param("colsample_bytree", 0.8)

    mlflow.log_metric("rmse", rmse_xgb)

🏃 View run xgboost_v1 at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0/runs/443bc6e0e0d74fe9b39ebb2e8714fe37
🧪 View experiment at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0

In [193]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

In [194]:
rf = RandomForestRegressor(
    n_estimators=400,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=400, n_jobs=-1, random_state=42)

In [195]:
preds_rf = rf.predict(X_val)

rmse_rf = np.sqrt(mean_squared_error(y_val, preds_rf))

print("Random Forest RMSE:", rmse_rf)

Random Forest RMSE: 0.14559789393237513

In [196]:
import mlflow

with mlflow.start_run(run_name="random_forest_v1"):
    mlflow.log_param("model", "RandomForestRegressor")
    mlflow.log_param("n_estimators", 400)
    mlflow.log_param("max_depth", None)
    mlflow.log_param("min_samples_split", 2)
    mlflow.log_param("min_samples_leaf", 1)

    mlflow.log_metric("rmse", rmse_rf)

🏃 View run random_forest_v1 at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0/runs/0956afeef1544538b6ff01a1f58796ca
🧪 View experiment at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0

In [197]:
from sklearn.linear_model import Ridge

X_full = df_final.drop("SalePrice", axis=1)
X_full = X_full.drop(columns=drop_cols, errors="ignore")
y_full = np.log1p(df_final["SalePrice"])

final_model = Ridge(alpha=10.0)
final_model.fit(X_full, y_full)

Ridge(alpha=10.0)

In [198]:
print("Final model trained on full data.")
print("Estimated RMSE from K-Fold: 0.12505")

Final model trained on full data.
Estimated RMSE from K-Fold: 0.12505

In [199]:
import mlflow
import mlflow.sklearn

with mlflow.start_run(run_name="ridge_manual_drop_final"):
    mlflow.log_param("model", "Ridge")
    mlflow.log_param("alpha", 10)
    mlflow.log_param("feature_selection", "manual_drop")
    mlflow.log_metric("cv_mean_rmse", 0.12505)  

    mlflow.sklearn.log_model(
        sk_model=final_model,
        name="model",
        registered_model_name="house_prices_ridge_manual"
    )

2026/04/12 13:33:07 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Registered model 'house_prices_ridge_manual' already exists. Creating a new version of this model...
2026/04/12 13:33:19 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: house_prices_ridge_manual, version 20
Created version '20' of model 'house_prices_ridge_manual'.

🏃 View run ridge_manual_drop_final at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0/runs/ff054f5333e74043a7ec6dd5eaaf2d01
🧪 View experiment at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0

In [200]:
import mlflow.sklearn

with mlflow.start_run(run_name="ridge_final_model"):
    mlflow.log_param("model", "Ridge")
    mlflow.log_param("alpha", 10)
    mlflow.log_metric("rmse", rmse)
    
    mlflow.sklearn.log_model(
        final_model,
        name="ridge_model",
        registered_model_name="RidgeHousePrices" 
    )

2026/04/12 13:33:29 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Registered model 'RidgeHousePrices' already exists. Creating a new version of this model...
2026/04/12 13:33:43 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: RidgeHousePrices, version 9
Created version '9' of model 'RidgeHousePrices'.

🏃 View run ridge_final_model at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0/runs/58a87991eddc4c309a05998bcaeee2f4
🧪 View experiment at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0

In [201]:
import mlflow.sklearn
import joblib
import os

with mlflow.start_run(run_name="ridge_final_model"):
    mlflow.log_param("model", "Ridge")
    mlflow.log_param("alpha", 10)
    mlflow.log_metric("rmse", rmse)
    
    mlflow.sklearn.log_model(
        final_model,
        name="ridge_model",
        registered_model_name="RidgeHousePrices"
    )
    
    joblib.dump(list(X_full.columns), "model_columns.pkl")
    mlflow.log_artifact("model_columns.pkl")

2026/04/12 13:33:54 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Registered model 'RidgeHousePrices' already exists. Creating a new version of this model...
2026/04/12 13:34:06 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: RidgeHousePrices, version 10
Created version '10' of model 'RidgeHousePrices'.

🏃 View run ridge_final_model at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0/runs/2c5903b123e6470b8d736bb29bd073ea
🧪 View experiment at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0

# KFold

In [202]:
from sklearn.model_selection import KFold
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
import numpy as np

X_full_kf = df_final.drop("SalePrice", axis=1)
X_full_kf = X_full_kf.drop(columns=drop_cols, errors="ignore")
y_full_kf = np.log1p(df_final["SalePrice"])

kf = KFold(n_splits=5, shuffle=True, random_state=42)

rmse_folds = []

for alpha in [0.1, 1.0, 10.0, 50.0]:
    rmse_folds = []
    for fold, (train_idx, val_idx) in enumerate(kf.split(X_full), 1):
        X_tr, X_val_kf = X_full.iloc[train_idx], X_full.iloc[val_idx]
        y_tr, y_val_kf = y_full.iloc[train_idx], y_full.iloc[val_idx]

        model_kf = Ridge(alpha=alpha)
        model_kf.fit(X_tr, y_tr)
        preds_kf = model_kf.predict(X_val_kf)
        rmse_folds.append(np.sqrt(mean_squared_error(y_val_kf, preds_kf)))

    print(f"Alpha {alpha:5} -> Mean RMSE: {np.mean(rmse_folds):.5f}  Std: {np.std(rmse_folds):.5f}")

Alpha   0.1 -> Mean RMSE: 0.12505  Std: 0.00924
Alpha   1.0 -> Mean RMSE: 0.11886  Std: 0.00701
Alpha  10.0 -> Mean RMSE: 0.11483  Std: 0.00708
Alpha  50.0 -> Mean RMSE: 0.11575  Std: 0.00824

In [203]:
with mlflow.start_run(run_name="kfold_cv_ridge_manual"):
    mlflow.log_param("model", "Ridge")
    mlflow.log_param("alpha", 10)
    mlflow.log_param("cv_folds", 5)
    mlflow.log_param("feature_selection", "manual_drop")
    mlflow.log_metric("cv_mean_rmse", np.mean(rmse_folds))
    mlflow.log_metric("cv_std_rmse", np.std(rmse_folds))

🏃 View run kfold_cv_ridge_manual at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0/runs/51b634afb44342d5b0bc0d065c431f1b
🧪 View experiment at: https://dagshub.com/smama23/MLassignment1.mlflow/#/experiments/0